export const DICCIONARIO = new Map([

  // ─── SALUD ───────────────────────────────────────────────────────
  ["médico","doctor"],
  ["medico","doctor"],
  ["doctora","doctor"],
  ["doctor","doctor"],
  ["dentista","dentist"],
  ["farmacia","pharmacy"],
  ["medicina","medicine"],
  ["medicamento","medicine"],
  ["pastilla","pill"],
  ["pastillas","pills"],
  ["vacuna","vaccine"],
  ["análisis","blood test"],
  ["analisis","blood test"],
  ["operación","surgery"],
  ["operacion","surgery"],
  ["hospital","hospital"],
  ["urgencias","emergency"],
  ["revisión","checkup"],
  ["revision","checkup"],
  ["cita médica","doctor appointment"],
  ["fisio","physiotherapy"],
  ["fisioterapeuta","physiotherapist"],
  ["psicólogo","psychologist"],
  ["psicologo","psychologist"],
  ["ginecólogo","gynecologist"],
  ["ginecologia","gynecology"],
  ["oculista","optician"],
  ["oftalmólogo","ophthalmologist"],
  ["cardiólogo","cardiologist"],
  ["cardiologo","cardiologist"],
  ["ortopedia","orthopedics"],
  ["enfermero","nurse"],
  ["enfermera","nurse"],
  ["ambulancia","ambulance"],
  ["receta","prescription"],
  ["tensión","blood pressure"],
  ["tension","blood pressure"],
  ["glucosa","glucose"],
  ["colesterol","cholesterol"],
  ["dieta","diet"],
  ["nutricionista","nutritionist"],
  ["terapia","therapy"],
  ["rehabilitación","rehabilitation"],
  ["rehabilitacion","rehabilitation"],
  ["cirugía","surgery"],
  ["cirugia","surgery"],
  ["radiografía","x-ray"],

  // ─── ANIMALES ────────────────────────────────────────────────────
  ["gato","cat"],
  ["gata","cat"],
  ["gatito","kitten"],
  ["perro","dog"],
  ["perra","dog"],
  ["cachorro","puppy"],
  ["pez","fish"],
  ["peces","fish"],
  ["pájaro","bird"],
  ["pajaro","bird"],
  ["conejo","rabbit"],
  ["hámster","hamster"],
  ["hamster","hamster"],
  ["tortuga","turtle"],
  ["loro","parrot"],
  ["caballo","horse"],
  ["vaca","cow"],
  ["gallina","hen"],
  ["gallo","rooster"],
  ["pato","duck"],
  ["cobaya","guinea pig"],
  ["hurón","ferret"],
  ["huron","ferret"],
  ["iguana","iguana"],
  ["veterinario","vet"],
  ["veterinaria","vet"],
  ["peluquero canino","dog groomer"],
  ["correa","leash"],
  ["collar","collar"],
  ["microchip","microchip"],
  ["desparasitar","deworming"],
  ["antiparasitario","antiparasitic"],
  ["pienso","pet food"],
  ["croquetas","kibble"],
  ["arenero","litter box"],
  ["pipican","dog park"],
  ["jaula","cage"],
  ["acuario","aquarium"],
  ["terrario","terrarium"],
  ["comedero","feeder"],
  ["bebedero","water bowl"],

  // ─── HOGAR ───────────────────────────────────────────────────────
  ["limpieza","cleaning"],
  ["limpiar","cleaning"],
  ["barrer","sweeping"],
  ["fregar","mopping"],
  ["aspirar","vacuuming"],
  ["planchar","ironing"],
  ["lavar","washing"],
  ["ropa","clothes"],
  ["lavadora","washing machine"],
  ["secadora","dryer"],
  ["tendedero","clothesline"],
  ["basura","trash"],
  ["reciclar","recycling"],
  ["contenedor","container"],
  ["mudanza","moving"],
  ["muebles","furniture"],
  ["fontanero","plumber"],
  ["electricista","electrician"],
  ["albañil","builder"],
  ["pintor","painter"],
  ["carpintero","carpenter"],
  ["reparación","repair"],
  ["reparacion","repair"],
  ["avería","breakdown"],
  ["averia","breakdown"],
  ["mantenimiento","maintenance"],
  ["alarma casa","home alarm"],
  ["cerradura","lock"],
  ["llave","key"],
  ["buzón","mailbox"],
  ["buzon","mailbox"],

  // ─── SUMINISTROS Y FACTURAS ──────────────────────────────────────
  ["factura","bill"],
  ["luz","electricity"],
  ["gas","gas"],
  ["internet","internet"],
  ["agua","water"],
  ["alquiler","rent"],
  ["hipoteca","mortgage"],
  ["seguro","insurance"],
  ["comunidad","community fee"],
  ["ibi","property tax"],
  ["impuesto","tax"],
  ["multa","fine"],
  ["recibo","receipt"],
  ["pago","payment"],
  ["domiciliación","direct debit"],
  ["domiciliacion","direct debit"],

  // ─── JARDÍN Y PLANTAS ────────────────────────────────────────────
  ["regar","watering"],
  ["plantas","plants"],
  ["planta","plant"],
  ["jardín","garden"],
  ["jardin","garden"],
  ["piscina","pool"],
  ["césped","lawn"],
  ["cesped","lawn"],
  ["abono","fertilizer"],
  ["maceta","pot"],
  ["semillas","seeds"],
  ["poda","pruning"],
  ["flores","flowers"],
  ["huerto","vegetable garden"],

  // ─── COMIDA Y BEBIDA ─────────────────────────────────────────────
  ["desayuno","breakfast"],
  ["almuerzo","lunch"],
  ["comida","food"],
  ["cena","dinner"],
  ["merienda","snack"],
  ["café","coffee"],
  ["cafe","coffee"],
  ["té","tea"],
  ["zumo","juice"],
  ["batido","smoothie"],
  ["cerveza","beer"],
  ["vino","wine"],
  ["pizza","pizza"],
  ["pasta","pasta"],
  ["arroz","rice"],
  ["pan","bread"],
  ["fruta","fruit"],
  ["verdura","vegetables"],
  ["carne","meat"],
  ["pescado","fish"],
  ["marisco","seafood"],
  ["huevos","eggs"],
  ["leche","milk"],
  ["queso","cheese"],
  ["yogur","yogurt"],
  ["helado","ice cream"],
  ["postre","dessert"],
  ["tarta","cake"],
  ["restaurante","restaurant"],
  ["bar","bar"],
  ["cafetería","cafeteria"],
  ["cafeteria","cafeteria"],
  ["panadería","bakery"],
  ["panaderia","bakery"],
  ["carnicería","butcher"],
  ["pescadería","fishmonger"],
  ["comer","eating"],
  ["cocinar","cooking"],

  // ─── COMPRAS ─────────────────────────────────────────────────────
  ["compra","shopping"],
  ["compras","shopping"],
  ["mercado","market"],
  ["supermercado","supermarket"],
  ["centro comercial","shopping mall"],
  ["tienda","store"],
  ["quiosco","kiosk"],
  ["verdulería","greengrocer"],
  ["ferretería","hardware store"],
  ["ferreteria","hardware store"],
  ["librería","bookstore"],
  ["libreria","bookstore"],
  ["zapatería","shoe store"],
  ["zapateria","shoe store"],

  // ─── TRABAJO Y ESTUDIOS ──────────────────────────────────────────
  ["trabajo","work"],
  ["trabajar","work"],
  ["oficina","office"],
  ["reunión","meeting"],
  ["reunion","meeting"],
  ["jefe","boss"],
  ["cliente","client"],
  ["proyecto","project"],
  ["entrega","delivery"],
  ["deadline","deadline"],
  ["informe","report"],
  ["presentación","presentation"],
  ["presentacion","presentation"],
  ["llamada","call"],
  ["videoconferencia","video call"],
  ["email","email"],
  ["correo","email"],
  ["contrato","contract"],
  ["nómina","payroll"],
  ["nomina","payroll"],
  ["entrevista","interview"],
  ["formación","training"],
  ["formacion","training"],
  ["congreso","conference"],
  ["seminario","seminar"],
  ["taller","workshop"],
  ["estudio","study"],
  ["estudiar","study"],
  ["examen","exam"],
  ["clase","class"],
  ["curso","course"],
  ["universidad","university"],
  ["instituto","high school"],
  ["biblioteca","library"],
  ["deberes","homework"],
  ["trabajo fin de grado","thesis"],
  ["tfg","thesis"],
  ["tfm","master thesis"],
  ["oposición","public exam"],
  ["oposicion","public exam"],

  // ─── TRANSPORTE ──────────────────────────────────────────────────
  ["coche","car"],
  ["carro","car"],
  ["moto","motorcycle"],
  ["bici","bike"],
  ["bicicleta","bicycle"],
  ["patinete","scooter"],
  ["bus","bus"],
  ["autobús","bus"],
  ["autobus","bus"],
  ["metro","subway"],
  ["tren","train"],
  ["avión","plane"],
  ["avion","plane"],
  ["vuelo","flight"],
  ["aeropuerto","airport"],
  ["taxi","taxi"],
  ["uber","uber"],
  ["gasolina","gasoline"],
  ["gasolinera","gas station"],
  ["aparcamiento","parking"],
  ["garaje","garage"],
  ["itv","car inspection"],
  ["seguro coche","car insurance"],
  ["cambio aceite","oil change"],
  ["revisión coche","car service"],
  ["neumáticos","tires"],
  ["neumaticos","tires"],
  ["batería","battery"],
  ["bateria","battery"],

  // ─── DEPORTE Y EJERCICIO ─────────────────────────────────────────
  ["gimnasio","gym"],
  ["gym","gym"],
  ["ejercicio","exercise"],
  ["entrenar","training"],
  ["entrenamiento","training"],
  ["correr","running"],
  ["caminar","walking"],
  ["nadar","swimming"],
  ["yoga","yoga"],
  ["pilates","pilates"],
  ["fútbol","football"],
  ["futbol","football"],
  ["baloncesto","basketball"],
  ["tenis","tennis"],
  ["padel","paddle tennis"],
  ["pádel","paddle tennis"],
  ["ciclismo","cycling"],
  ["montaña","mountain"],
  ["senderismo","hiking"],
  ["boxeo","boxing"],
  ["crossfit","crossfit"],
  ["pesas","weights"],
  ["cardio","cardio"],
  ["natación","swimming"],
  ["natacion","swimming"],
  ["atletismo","athletics"],
  ["escalada","climbing"],
  ["surf","surfing"],
  ["esquí","skiing"],
  ["esqi","skiing"],
  ["kárate","karate"],
  ["karate","karate"],
  ["judo","judo"],
  ["muay thai","muay thai"],
  ["artes marciales","martial arts"],
  ["estiramientos","stretching"],
  ["meditación","meditation"],
  ["meditacion","meditation"],
  ["running","running"],

  // ─── FINANZAS ────────────────────────────────────────────────────
  ["banco","bank"],
  ["cajero","atm"],
  ["transferencia","transfer"],
  ["deuda","debt"],
  ["préstamo","loan"],
  ["prestamo","loan"],
  ["inversión","investment"],
  ["inversion","investment"],
  ["ahorro","savings"],
  ["declaración renta","income tax return"],
  ["declaracion renta","income tax return"],
  ["gestoría","agency"],
  ["gestoria","agency"],
  ["hacienda","tax office"],
  ["seguridad social","social security"],
  ["paro","unemployment"],
  ["autonomo","self-employed"],
  ["autónomo","self-employed"],
  ["facturar","invoice"],
  ["presupuesto","budget"],

  // ─── OCIO Y CULTURA ──────────────────────────────────────────────
  ["cine","cinema"],
  ["película","movie"],
  ["pelicula","movie"],
  ["teatro","theater"],
  ["concierto","concert"],
  ["música","music"],
  ["musica","music"],
  ["libro","book"],
  ["leer","reading"],
  ["museo","museum"],
  ["exposición","exhibition"],
  ["exposicion","exhibition"],
  ["viaje","travel"],
  ["vacaciones","vacation"],
  ["hotel","hotel"],
  ["playa","beach"],
  ["fiesta","party"],
  ["cumpleaños","birthday"],
  ["boda","wedding"],
  ["evento","event"],
  ["aniversario","anniversary"],
  ["excursión","excursion"],
  ["excursion","excursion"],
  ["espectáculo","show"],
  ["espectaculo","show"],
  ["festival","festival"],
  ["feria","fair"],
  ["circo","circus"],
  ["parque","park"],
  ["parque de atracciones","theme park"],
  ["zoo","zoo"],
  ["escape room","escape room"],

  // ─── VIDEOJUEGOS ─────────────────────────────────────────────────
  ["videojuego","video game"],
  ["videojuegos","video games"],
  ["juego","game"],
  ["juegos","games"],
  ["raid","raid"],
  ["misión","mission"],
  ["mision","mission"],
  ["partida","game session"],
  ["torneo","tournament"],
  ["servidor","server"],
  ["actualización","update"],
  ["actualizacion","update"],
  ["dlc","dlc"],
  ["expansión","expansion"],
  ["expansion","expansion"],
  ["clan","clan"],
  ["gremio","guild"],
  ["mazmorra","dungeon"],
  ["boss","boss"],
  ["jefe final","final boss"],
  ["multijugador","multiplayer"],
  ["ranked","ranked"],
  ["temporada","season"],
  ["battle pass","battle pass"],
  ["pase de batalla","battle pass"],
  ["loot","loot"],
  ["crafting","crafting"],
  ["skin","skin"],
  ["personaje","character"],
  ["nivel","level"],
  ["logro","achievement"],
  ["minecraft","minecraft"],
  ["fortnite","fortnite"],
  ["valorant","valorant"],
  ["lol","league of legends"],
  ["league of legends","league of legends"],
  ["gta","gta"],
  ["zelda","zelda"],
  ["mario","mario"],
  ["pokemon","pokemon"],
  ["fifa","fifa"],
  ["cod","call of duty"],
  ["call of duty","call of duty"],
  ["warzone","warzone"],
  ["apex","apex legends"],
  ["apex legends","apex legends"],
  ["overwatch","overwatch"],
  ["destiny","destiny"],
  ["wow","world of warcraft"],
  ["world of warcraft","world of warcraft"],
  ["elden ring","elden ring"],
  ["cyberpunk","cyberpunk"],
  ["witcher","the witcher"],
  ["the witcher","the witcher"],
  ["skyrim","skyrim"],
  ["hogwarts","hogwarts legacy"],
  ["hogwarts legacy","hogwarts legacy"],
  ["starfield","starfield"],
  ["diablo","diablo"],
  ["hearthstone","hearthstone"],
  ["hollow knight","hollow knight"],
  ["hades","hades"],
  ["celeste","celeste"],
  ["stardew valley","stardew valley"],
  ["among us","among us"],
  ["fall guys","fall guys"],
  ["rocket league","rocket league"],
  ["street fighter","street fighter"],
  ["mortal kombat","mortal kombat"],
  ["tekken","tekken"],
  ["resident evil","resident evil"],
  ["silent hill","silent hill"],
  ["final fantasy","final fantasy"],
  ["dark souls","dark souls"],
  ["bloodborne","bloodborne"],
  ["sekiro","sekiro"],
  ["god of war","god of war"],
  ["spider-man","spider-man"],
  ["horizon","horizon"],
  ["assassins creed","assassins creed"],
  ["far cry","far cry"],
  ["the last of us","the last of us"],
  ["red dead","red dead redemption"],
  ["animal crossing","animal crossing"],
  ["splatoon","splatoon"],
  ["metroid","metroid"],
  ["kirby","kirby"],
  ["smash bros","super smash bros"],
  ["directive 8020","video game"],
  ["directive","video game"],
  ["palworld","palworld"],
  ["enshrouded","enshrouded"],
  ["helldivers","helldivers"],
  ["baldurs gate","baldurs gate"],
  ["lies of p","lies of p"],
  ["armored core","armored core"],

  // ─── CULTURA POP / ENTRETENIMIENTO ───────────────────────────────
  ["serie","tv series"],
  ["series","tv series"],
  ["anime","anime"],
  ["manga","manga"],
  ["comic","comic"],
  ["cómic","comic"],
  ["marvel","marvel"],
  ["dc","dc comics"],
  ["star wars","star wars"],
  ["harry potter","harry potter"],
  ["señor de los anillos","lord of the rings"],
  ["got","game of thrones"],
  ["game of thrones","game of thrones"],
  ["breaking bad","breaking bad"],
  ["stranger things","stranger things"],
  ["mandalorian","the mandalorian"],
  ["netflix","netflix"],
  ["disney","disney"],
  ["hbo","hbo"],
  ["prime video","amazon prime video"],
  ["apple tv","apple tv"],
  ["streaming","streaming"],
  ["podcast","podcast"],
  ["youtube","youtube"],
  ["twitch","twitch"],
  ["tiktok","tiktok"],
  ["instagram","instagram"],
  ["documental","documentary"],
  ["maratón series","tv marathon"],
  ["maraton series","tv marathon"],

  // ─── PERSONAL Y SOCIAL ───────────────────────────────────────────
  ["llamar","call"],
  ["mensaje","message"],
  ["whatsapp","whatsapp"],
  ["telegram","telegram"],
  ["amigo","friend"],
  ["amigos","friends"],
  ["familia","family"],
  ["madre","mother"],
  ["padre","father"],
  ["hijo","child"],
  ["hija","child"],
  ["hermano","brother"],
  ["hermana","sister"],
  ["abuelo","grandfather"],
  ["abuela","grandmother"],
  ["pareja","partner"],
  ["novio","boyfriend"],
  ["novia","girlfriend"],
  ["regalo","gift"],
  ["peluquería","hairdresser"],
  ["peluqueria","hairdresser"],
  ["barbería","barbershop"],
  ["barberia","barbershop"],
  ["uñas","nails"],
  ["masaje","massage"],
  ["spa","spa"],
  ["estética","beauty salon"],
  ["estetica","beauty salon"],
  ["depilación","waxing"],
  ["depilacion","waxing"],
  ["tatuaje","tattoo"],
  ["piercing","piercing"],

  // ─── TRÁMITES Y GESTIONES ────────────────────────────────────────
  ["dni","id card"],
  ["pasaporte","passport"],
  ["carnet","card"],
  ["licencia","license"],
  ["permiso","permit"],
  ["certificado","certificate"],
  ["notario","notary"],
  ["registro","registry"],
  ["ayuntamiento","town hall"],
  ["correos","post office"],
  ["paquete","package"],
  ["envío","shipment"],
  ["envio","shipment"],
  ["devolución","return"],
  ["devolucion","return"],
  ["garantía","warranty"],
  ["garantia","warranty"],
  ["reclamación","complaint"],
  ["reclamacion","complaint"],
  ["cita previa","appointment"],
]);
